### ISSUE TITLE
software x64

### ISSUE THREAD

**Issue by TokyoKingPain** [tr1xongithub/RunPe#1]
is possible do this code to software x64 , like 

 printf("\nError: Invalid executable, must me x86 bit.\n");
 
 to be X64 instead of the file being

**Comment by tr1xongithub** [comment]
> is possible do this code to software x64 , like 
> 
> 
> 
>  printf("\nError: Invalid executable, must me x86 bit.\n");
> 
>  
> 
>  to be X64 instead of the file being

Yes it is possible
